### ISSUE TITLE
Sometimes a topic is not found by roswatcher thread...

### ISSUE THREAD

**Issue by asmodehn** [asmodehn/pyros#37]
[INFO] [WallTime: 1448446316.606745] [ros_interface] Adding service /._/stop_rapp
[WARN] [WallTime: 1448446316.620876] [ros_interface] Cannot Expose unknown service /._/stop_rapp (maybe it is a regex or doesn't exist yet?)  
[INFO] [WallTime: 1448446316.623403] [ros_interface] Exposing params : []
[INFO] [WallTime: 1448446316.624298] [ros_interface] Exposing actions : []
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/groot/rocon_ws/src/pyros/src/rostful_node/ros_watcher.py", line 55, in run
    self.update()
  File "/opt/groot/rocon_ws/src/pyros/src/rostful_node/ros_watcher.py", line 70, in update
    self.topics_change_cb([ c.name for c in new_conns[SUBSCRIBER]], [c.name for c in lost_conns[SUBSCRIBER]])
  File "/opt/groot/rocon_ws/src/pyros/src/rostful_node/ros_interface.py", line 506, in topics_change_cb
    ret = self.add_topic(topic_name)
  File "/opt/groot/rocon_ws/src/pyros/src/rostful_node/ros_interface.py", line 274, in add_topic
    if self.topics_args[topic_name] == -2:
KeyError: '/rocon/app_manager/rapp_list'

**Comment by asmodehn** [comment]
This seems to have been fixed while refactoring and testing for 0.1
