### ISSUE TITLE
unknown bug

### ISSUE THREAD

**Issue by asmodehn** [asmodehn/pyros#72]
```
Process rostful:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/rosinterface/pyros_ros.py", line 166, in run
    super(PyrosROS, self).run()  # we override parent run to add one argument to ros interface
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/baseinterface/basenode.py", line 109, in run
    super(PyrosBase, self).run()
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/zmp/node.py", line 262, in run
    self.update(timedelta)
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/baseinterface/basenode.py", line 130, in update
    self.update_throttled()
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/baseinterface/basenode.py", line 138, in update_throttled
    self.interface.update()
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/rosinterface/ros_interface.py", line 461, in update
    return super(RosInterface, self).update()
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/baseinterface/baseinterface.py", line 497, in update
    tdt = self.topics_change_detect()
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/baseinterface/baseinterface.py", line 203, in _transient_change_detect
    **class_build_kwargs
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/baseinterface/baseinterface.py", line 234, in _transient_change_diff
    **class_build_kwargs
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/baseinterface/baseinterface.py", line 127, in _update_transients
    class_clean_func(resolved_dict[tst_name])  # calling the cleanup function in case we need to do something
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/rosinterface/ros_interface.py", line 111, in TopicCleaner
    return topic.cleanup()
  File "/home/alexv/ROS/gopher_bootstrap/src/pyros/src/pyros/rosinterface/topic.py", line 157, in cleanup
    if_topics.remove(self.fullname)
ValueError: list.remove(x): x not in list
```

**Comment by asmodehn** [comment]
This hasnt been reproduced in a while...

Idea: to make traceback more explicit, and useful for debugging as a report, we should probably include version number in here somehow...
